import json
import os

import numpy as np

# Paths (Adjust if needed)
CONFIG_PATH = "../app/public/models/audio_config.json"
OUTPUT_PATH = "../app/public/models/golden_parity.json"


def load_matrices():
    if not os.path.exists(CONFIG_PATH):
        # Fallback if running from root
        alt = "app/public/models/audio_config.json"
        if os.path.exists(alt):
            return load_matrices_from_path(alt)
        print(f"❌ Error: Could not find {CONFIG_PATH}")
        return None
    return load_matrices_from_path(CONFIG_PATH)


def load_matrices_from_path(path):
    with open(path, "r") as f:
        config = json.load(f)
    return {
        "dft_real": np.array(config["dft_real"], dtype=np.float32),
        "dft_imag": np.array(config["dft_imag"], dtype=np.float32),
        "mel_basis": np.array(config["mel_basis"], dtype=np.float32),
        "dct_matrix": np.array(config["dct_matrix"], dtype=np.float32),
        "window": np.array(config["window"], dtype=np.float32),
    }


def compute_manual_mfcc(signal, mats):
    """
    Replicates the EXACT math from custom-extractor.ts
    """
    frame_len = 512
    hop_len = 256

    # 1. Framing Logic (Must match JS exactly)
    # JS: Math.floor((len - frame) / hop) + 1
    n_frames = int((len(signal) - frame_len) / hop_len) + 1

    print(f"🧮 Generating {n_frames} frames from {len(signal)} samples...")

    mfccs = []

    for i in range(n_frames):
        start = i * hop_len
        end = start + frame_len

        # Safety check for array bounds (JS subarray handles this gracefully, Python slices do too)
        if end > len(signal):
            break

        frame = signal[start:end]

        # 2. Windowing
        windowed = frame * mats["window"]

        # 3. DFT
        real = mats["dft_real"] @ windowed
        imag = mats["dft_imag"] @ windowed

        # 4. Magnitude (Not Power!)
        mag = np.sqrt(real ** 2 + imag ** 2)

        # 5. Mel Basis
        mel = mats["mel_basis"] @ mag

        # 6. Log (Natural Log, with 1e-6 epsilon)
        log_mel = np.log(mel + 1e-6)

        # 7. DCT
        mfcc = mats["dct_matrix"] @ log_mel
        mfccs.append(mfcc)

    return np.array(mfccs)  # Shape: [Frames, 40]


def generate():
    print("⚙️  Loading Matrices...")
    mats = load_matrices()
    if not mats: return

    # 1. Deterministic Signal
    sr = 22050
    signal = np.zeros(sr, dtype=np.float32)
    signal[0] = 1.0
    signal[sr // 2] = 0.5
    signal += 0.001

    print("🧮 Computing MFCCs using Pipeline Math...")
    try:
        expected_mfcc = compute_manual_mfcc(signal, mats)
    except Exception as e:
        print(f"❌ Math Error: {e}")
        return

    # 2. Save
    output = {
        "note": "Generated by generate_golden.py using audio_config.json matrices",
        "signal": signal.tolist(),
        "expected_mfcc": expected_mfcc.tolist()
    }

    with open(OUTPUT_PATH, 'w') as f:
        json.dump(output, f)

    print(f"✅ Saved golden reference to {OUTPUT_PATH}")
    print(f"   Shape: {expected_mfcc.shape}")
    print(f"   First Val: {expected_mfcc[0][0]}")
    print(f"   Now run checkStrictParity() in the App Console.")


if __name__ == "__main__":
    generate()
